# Generated by Django 3.1.2 on 2020-10-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='Description',
            field=models.TextField(),
        ),
    ]
