# Generated by Django 3.1.2 on 2020-11-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201031_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Comment',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
