# Generated by Django 3.1.2 on 2020-11-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201109_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Comment',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
