# Generated by Django 3.1.2 on 2020-11-09 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201110_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='Listing',
        ),
        migrations.AddField(
            model_name='listings',
            name='Categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='Category',
            field=models.CharField(max_length=20),
        ),
    ]
