# Generated by Django 3.1.2 on 2020-11-11 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201112_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='Creater',
            new_name='Creator',
        ),
    ]
