# Generated by Django 3.1.2 on 2020-11-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='Listing',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='auctions.Listings'),
        ),
    ]
