# Generated by Django 3.1.2 on 2020-11-12 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201112_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='Listing',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='auctions.Listings'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='Watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
