# Generated by Django 3.1.2 on 2020-11-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listings_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Comment',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
